{% set name = "heligeo" %}
{% set version = "1.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/heligeo-{{ version }}.tar.gz
  sha256: 04b0f22f52db2aedfd24a7b694d4f4585e17b9a0144a66199f459f3615b5e757

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - numpy
    - plotly
    - python >=3.0
    - requests
    - shapely

test:
  imports:
    - heligeo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NandanPattanayak/heligeo
  summary: Api that perform Visualization,Route,Isochrone and Geoprocessing Service
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NandanPattanayak
